### ISSUE TITLE
Ability to update the history for one user by handle

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/tc-tagger-api#7]
We already have an endoint `PUT /v5/tagger/member-profiles?startDate=&endDate=&challengeId=&stream=` which can update the history for the users for some period of time `startDate=&endDate=` or by for particular challenge `challengeId=`.

We would like to be able to update the history for one single user if we want to.

- Support new query param `PUT /v5/tagger/member-profiles?membeHandle=`
- If it's defined we have to get all the challenges where user won and put them into the history
- We already have a script that does it https://github.com/topcoder-platform/tc-tagger-api/blob/feature/batch-endpoints/scripts/tag-member.js so we can use the same logic
  - create reusable methods for parts of this script (don't need to update this script itself, later we would remove it)
- The only one difference from the script, that script now internally calls `PUT /v5/tagger/member-profiles?challengeId=` which update history for ALL the winners of that challenge. In our endpoint we have to only update the history for the selected user, not for all the users who won the same challenges.
- If we couldn't not get data of particular challenge log error, but code should still process other challenges.
- Update history for the member after getting data for each challenge, don't wait for all challenges. So in case something goes wrong and code stops at some moment, history in the DB would be updated for the challenge which already processed.

**Comment by RishiRajSahu** [comment]
@maxceem this is done as part of last migration challenge, right ?

**Comment by maxceem** [comment]
Right, it's done, closing it.
